on: push
name: Linting check
jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0 libdbus-1-dev
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy
          override: true
      - run: npm run build
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-targets --manifest-path src-tauri/Cargo.toml