on:
  push:
    branches-ignore:
      - 'dependabot/**'
name: Linting check
jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0 libdbus-1-dev
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy
          override: true
      - run: mkdir dist
      - uses: actions-rs/clippy-check@v1
        with:
          args: --all-targets --manifest-path src-tauri/Cargo.toml
